// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type PackingItem struct {
	ID          int32          `json:"id"`
	TripID      string         `json:"trip_id"`
	Name        string         `json:"name"`
	Category    string         `json:"category"`
	IsEssential bool           `json:"is_essential"`
	Reason      sql.NullString `json:"reason"`
	IsChecked   bool           `json:"is_checked"`
	SortOrder   int32          `json:"sort_order"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Trip struct {
	ID            string          `json:"id"`
	Destination   string          `json:"destination"`
	DestLat       string          `json:"dest_lat"`
	DestLon       string          `json:"dest_lon"`
	DepartureDate time.Time       `json:"departure_date"`
	ReturnDate    time.Time       `json:"return_date"`
	TripType      string          `json:"trip_type"`
	Companions    string          `json:"companions"`
	Activities    json.RawMessage `json:"activities"`
	CreatedAt     time.Time       `json:"created_at"`
}

type WeatherSnapshot struct {
	ID            int32           `json:"id"`
	TripID        string          `json:"trip_id"`
	TempMinF      int32           `json:"temp_min_f"`
	TempMaxF      int32           `json:"temp_max_f"`
	RainDays      int32           `json:"rain_days"`
	SnowDays      int32           `json:"snow_days"`
	IsForecast    bool            `json:"is_forecast"`
	DailyForecast json.RawMessage `json:"daily_forecast"`
	FetchedAt     time.Time       `json:"fetched_at"`
}
