// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: packing_items.sql

package db

import (
	"context"
	"database/sql"
)

const getItemsByTripID = `-- name: GetItemsByTripID :many
SELECT id, trip_id, name, category, is_essential, reason, is_checked, sort_order, created_at
FROM packing_items
WHERE trip_id = ?
ORDER BY sort_order ASC
`

func (q *Queries) GetItemsByTripID(ctx context.Context, tripID string) ([]PackingItem, error) {
	rows, err := q.db.QueryContext(ctx, getItemsByTripID, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PackingItem
	for rows.Next() {
		var i PackingItem
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Name,
			&i.Category,
			&i.IsEssential,
			&i.Reason,
			&i.IsChecked,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPackingItem = `-- name: InsertPackingItem :exec
INSERT INTO packing_items (trip_id, name, category, is_essential, reason, is_checked, sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertPackingItemParams struct {
	TripID      string         `json:"trip_id"`
	Name        string         `json:"name"`
	Category    string         `json:"category"`
	IsEssential bool           `json:"is_essential"`
	Reason      sql.NullString `json:"reason"`
	IsChecked   bool           `json:"is_checked"`
	SortOrder   int32          `json:"sort_order"`
}

func (q *Queries) InsertPackingItem(ctx context.Context, arg InsertPackingItemParams) error {
	_, err := q.db.ExecContext(ctx, insertPackingItem,
		arg.TripID,
		arg.Name,
		arg.Category,
		arg.IsEssential,
		arg.Reason,
		arg.IsChecked,
		arg.SortOrder,
	)
	return err
}

const updateItemChecked = `-- name: UpdateItemChecked :exec
UPDATE packing_items
SET is_checked = ?
WHERE id = ? AND trip_id = ?
`

type UpdateItemCheckedParams struct {
	IsChecked bool   `json:"is_checked"`
	ID        int32  `json:"id"`
	TripID    string `json:"trip_id"`
}

func (q *Queries) UpdateItemChecked(ctx context.Context, arg UpdateItemCheckedParams) error {
	_, err := q.db.ExecContext(ctx, updateItemChecked, arg.IsChecked, arg.ID, arg.TripID)
	return err
}
