// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetItemsByTripID(ctx context.Context, tripID string) ([]PackingItem, error)
	GetTripByID(ctx context.Context, id string) (Trip, error)
	GetWeatherByTripID(ctx context.Context, tripID string) (WeatherSnapshot, error)
	InsertPackingItem(ctx context.Context, arg InsertPackingItemParams) error
	InsertTrip(ctx context.Context, arg InsertTripParams) error
	InsertWeatherSnapshot(ctx context.Context, arg InsertWeatherSnapshotParams) error
	UpdateItemChecked(ctx context.Context, arg UpdateItemCheckedParams) error
}

var _ Querier = (*Queries)(nil)
