// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trips.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const deleteTrip = `-- name: DeleteTrip :exec
DELETE FROM trips WHERE id = ?
`

func (q *Queries) DeleteTrip(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTrip, id)
	return err
}

const getTripByID = `-- name: GetTripByID :one
SELECT id, destination, dest_lat, dest_lon, departure_date, return_date, trip_type, companions, activities, created_at
FROM trips
WHERE id = ?
`

func (q *Queries) GetTripByID(ctx context.Context, id string) (Trip, error) {
	row := q.db.QueryRowContext(ctx, getTripByID, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.Destination,
		&i.DestLat,
		&i.DestLon,
		&i.DepartureDate,
		&i.ReturnDate,
		&i.TripType,
		&i.Companions,
		&i.Activities,
		&i.CreatedAt,
	)
	return i, err
}

const insertTrip = `-- name: InsertTrip :exec
INSERT INTO trips (id, destination, dest_lat, dest_lon, departure_date, return_date, trip_type, companions, activities)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTripParams struct {
	ID            string          `json:"id"`
	Destination   string          `json:"destination"`
	DestLat       string          `json:"dest_lat"`
	DestLon       string          `json:"dest_lon"`
	DepartureDate time.Time       `json:"departure_date"`
	ReturnDate    time.Time       `json:"return_date"`
	TripType      string          `json:"trip_type"`
	Companions    string          `json:"companions"`
	Activities    json.RawMessage `json:"activities"`
}

func (q *Queries) InsertTrip(ctx context.Context, arg InsertTripParams) error {
	_, err := q.db.ExecContext(ctx, insertTrip,
		arg.ID,
		arg.Destination,
		arg.DestLat,
		arg.DestLon,
		arg.DepartureDate,
		arg.ReturnDate,
		arg.TripType,
		arg.Companions,
		arg.Activities,
	)
	return err
}

const updateTrip = `-- name: UpdateTrip :exec
UPDATE trips
SET destination = ?, dest_lat = ?, dest_lon = ?,
    departure_date = ?, return_date = ?,
    trip_type = ?, companions = ?, activities = ?
WHERE id = ?
`

type UpdateTripParams struct {
	Destination   string          `json:"destination"`
	DestLat       string          `json:"dest_lat"`
	DestLon       string          `json:"dest_lon"`
	DepartureDate time.Time       `json:"departure_date"`
	ReturnDate    time.Time       `json:"return_date"`
	TripType      string          `json:"trip_type"`
	Companions    string          `json:"companions"`
	Activities    json.RawMessage `json:"activities"`
	ID            string          `json:"id"`
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) error {
	_, err := q.db.ExecContext(ctx, updateTrip,
		arg.Destination,
		arg.DestLat,
		arg.DestLon,
		arg.DepartureDate,
		arg.ReturnDate,
		arg.TripType,
		arg.Companions,
		arg.Activities,
		arg.ID,
	)
	return err
}
