// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weather_snapshots.sql

package db

import (
	"context"
	"encoding/json"
)

const getWeatherByTripID = `-- name: GetWeatherByTripID :one
SELECT id, trip_id, temp_min_f, temp_max_f, rain_days, snow_days, is_forecast, daily_forecast, fetched_at
FROM weather_snapshots
WHERE trip_id = ?
`

func (q *Queries) GetWeatherByTripID(ctx context.Context, tripID string) (WeatherSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getWeatherByTripID, tripID)
	var i WeatherSnapshot
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.TempMinF,
		&i.TempMaxF,
		&i.RainDays,
		&i.SnowDays,
		&i.IsForecast,
		&i.DailyForecast,
		&i.FetchedAt,
	)
	return i, err
}

const insertWeatherSnapshot = `-- name: InsertWeatherSnapshot :exec
INSERT INTO weather_snapshots (trip_id, temp_min_f, temp_max_f, rain_days, snow_days, is_forecast, daily_forecast)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertWeatherSnapshotParams struct {
	TripID        string          `json:"trip_id"`
	TempMinF      int32           `json:"temp_min_f"`
	TempMaxF      int32           `json:"temp_max_f"`
	RainDays      int32           `json:"rain_days"`
	SnowDays      int32           `json:"snow_days"`
	IsForecast    bool            `json:"is_forecast"`
	DailyForecast json.RawMessage `json:"daily_forecast"`
}

func (q *Queries) InsertWeatherSnapshot(ctx context.Context, arg InsertWeatherSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, insertWeatherSnapshot,
		arg.TripID,
		arg.TempMinF,
		arg.TempMaxF,
		arg.RainDays,
		arg.SnowDays,
		arg.IsForecast,
		arg.DailyForecast,
	)
	return err
}
